config/routes.rb
PBTrustRails::Application.routes.draw do
  devise_for :users
  resources :feedbacks

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  get '/about' => 'home#about'
  get '/awards' => 'home#awards'
  get '/nomination_procedure' => 'home#nomination_procedure'
  get '/contact' => 'home#contact'
  root 'home#index'

  

end

app/models/about_data.rb
class AboutData < ActiveRecord::Base
  has_attached_file :avatar
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
end

app/models/award_data.rb
class AwardData < ActiveRecord::Base
  has_attached_file :avatar
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
end

app/models/contact_data.rb
class ContactData < ActiveRecord::Base
  has_attached_file :avatar
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
end

app/models/feedback.rb
class Feedback < ActiveRecord::Base
end

app/models/index_data.rb
class IndexData < ActiveRecord::Base
  has_attached_file :avatar
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
end

app/models/np_data.rb
class NpData < ActiveRecord::Base
  has_attached_file :avatar
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  layout :layout_by_resource

  protected

  def layout_by_resource
    if devise_controller?
      false
    else
      "application"
    end
  end
end

app/controllers/feedbacks_controller.rb
class FeedbacksController < ApplicationController
  before_action :set_feedback, only: [:show, :edit, :update, :destroy]

  # GET /feedbacks
  # GET /feedbacks.json
  def index
    @feedbacks = Feedback.all
  end

  # GET /feedbacks/1
  # GET /feedbacks/1.json
  def show
  end

  # GET /feedbacks/new
  def new
    @feedback = Feedback.new
  end

  # GET /feedbacks/1/edit
  def edit
  end

  # POST /feedbacks
  # POST /feedbacks.json
  def create
    @feedback = Feedback.new(feedback_params)

    respond_to do |format|
      if @feedback.save
        format.html { redirect_to "/contact", notice: 'Message Sent' }
        format.json { render action: 'show', status: :created, location: @feedback }
      else
        format.html { render action: 'new' }
        format.json { render json: @feedback.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /feedbacks/1
  # PATCH/PUT /feedbacks/1.json
  def update
    respond_to do |format|
      if @feedback.update(feedback_params)
        format.html { redirect_to @feedback, notice: 'Feedback was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @feedback.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /feedbacks/1
  # DELETE /feedbacks/1.json
  def destroy
    @feedback.destroy
    respond_to do |format|
      format.html { redirect_to feedbacks_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_feedback
      @feedback = Feedback.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def feedback_params
      params.require(:feedback).permit(:firstname, :lastname, :email, :comments)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    render :layout => false
  end

  def about
    #render :layout => false
  end

  def awards
    #render :layout => false
  end

  def nomination_procedure
    #render :text => false
  end

  def contact
    #render :text => false
    @feedback = Feedback.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/feedbacks_helper.rb
module FeedbacksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/feedbacks/_form.html.erb
<%= form_for(@feedback) do |f| %>
  <% if @feedback.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@feedback.errors.count, "error") %> prohibited this feedback from being saved:</h2>

      <ul>
      <% @feedback.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :firstname %><br>
    <%= f.text_field :firstname %>
  </div>
  <div class="field">
    <%= f.label :lastname %><br>
    <%= f.text_field :lastname %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :comments %><br>
    <%= f.text_area :comments %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/feedbacks/edit.html.erb
<h1>Editing feedback</h1>

<%= render 'form' %>

<%= link_to 'Show', @feedback %> |
<%= link_to 'Back', feedbacks_path %>

app/views/feedbacks/index.html.erb
<h1>Listing feedbacks</h1>

<table>
  <thead>
    <tr>
      <th>Firstname</th>
      <th>Lastname</th>
      <th>Email</th>
      <th>Comments</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @feedbacks.each do |feedback| %>
      <tr>
        <td><%= feedback.firstname %></td>
        <td><%= feedback.lastname %></td>
        <td><%= feedback.email %></td>
        <td><%= feedback.comments %></td>
        <td><%= link_to 'Show', feedback %></td>
        <td><%= link_to 'Edit', edit_feedback_path(feedback) %></td>
        <td><%= link_to 'Destroy', feedback, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Feedback', new_feedback_path %>

app/views/feedbacks/new.html.erb
<h1>New feedback</h1>

<%= render 'form' %>

<%= link_to 'Back', feedbacks_path %>

app/views/feedbacks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Firstname:</strong>
  <%= @feedback.firstname %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @feedback.lastname %>
</p>

<p>
  <strong>Email:</strong>
  <%= @feedback.email %>
</p>

<p>
  <strong>Comments:</strong>
  <%= @feedback.comments %>
</p>

<%= link_to 'Edit', edit_feedback_path(@feedback) %> |
<%= link_to 'Back', feedbacks_path %>

app/views/home/about.html.erb
<%= content_for :navbar do %>
    <ul class='wsite-menu-default'>
      <li id='pg102028352772474583'><a href='/'>Home</a></li>
      <li id='active'><a href='/about'>About</a></li>
      <li id='pg781891109137199263'><a href='/awards'>Awards</a></li>
      <li id='pg744403079724393911'><a href='/nomination_procedure'>Nomination Procedure</a></li>
      <li id='pg783104721222161831'><a href='/contact'>Contact</a></li>
    </ul>
<% end %>
<div id="main">
  <div id="main-inner">
    <div id="banner">
      <div id="banner-right">
        <div class="wsite-header"></div>
      </div>
    </div>
    <div id="content">
      <div id='wsite-content' class='wsite-elements wsite-not-footer'>
        <div>
          <div class="wsite-multicol">
            <div class='wsite-multicol-table-wrap' style='margin:0 -15px'>
              <table class='wsite-multicol-table'>
                <tbody class='wsite-multicol-tbody'>
                <tr class='wsite-multicol-tr'>
                  <td class='wsite-multicol-col' style='width:35%;padding:0 15px'>
                    <span class='imgPusher' style='float:left;height:0px;margin-top:19%;'></span>
                    <span style='z-index:10;position:relative;float:left;max-width:100%;;clear:left;margin-top:0px;*margin-top:0px'>
                     <a>
                       <img src="<%= AboutData.where(:key => "Image1").first.avatar.url %>" style="margin-top: 5px; margin-bottom: 10px;margin-left: 25px; margin-right: 10px; border-width:5px;padding:3px;" alt="Picture"  class="wsite-image"/>
                     </a>
                    <span
                  style="display: block; font-size: 90%; margin-top: -10px; margin-bottom: 10px; text-align: center;"
                  class="wsite-caption"></span></span>
                    <!-- <div class="paragraph" style="text-align:left;display:block;">The Prabhakar Barua Rhino Conservation Trust is set up by the children of Late Prabhakar Barua in memory of their father who was the&nbsp; first Assamese Chief Conservator of Forests of undivided Assam, a position which he held for thirteen long years from 1963 to 1976. A far sighted nature conservationist, he succeeded in creating an exceptional model in conservation, both in terms of forest areas protection and protection of the numerous threatened species of animals, culminating in the formation of the Assam Valley Wild-life Society of which he was the founder Vice- President. It was also during his tenure of office that Kaziranga was declared a National Park in 1974.</div -->
                    <!--<hr style="width:100%;clear:both;visibility:hidden;"></hr>-->

                    <div>
                      <div class="wsite-image wsite-image-border-thin "
                           style="padding-top:10px;padding-bottom:10px;margin-left:0;margin-right:0;text-align:center">
                        <!-- <a>
                        <img src="images/6634266.jpg?403" alt="Picture" style="width:auto;max-width:100%" />
                        </a> -->
                        <div style="display:block;font-size:90%"></div>
                      </div>
                    </div>

                  </td>
                  <td class='wsite-multicol-col' style='width:50%;padding:0 15px'>

                    <div>
                      <div class="wsite-image wsite-image-border-thin "
                           style="padding-top:10px;padding-bottom:10px;margin-left:0;margin-right:0;text-align:center">
                        <!-- <a>
                        <img src="images/7944979_orig.jpg" alt="Picture" style="width:100%;max-width:514px" />
                        </a> -->
                        <div style="display:block;font-size:90%">

                          <h2 class="wsite-content-title"
                              style="text-align:left;">
                            <strong><%= AboutData.where(:key => "AboutHeader").first.data %></strong></h2>

                          <div class="paragraph"
                               style="text-align:left;display:block;"><%= AboutData.where(:key => "AboutHeaderPara").first.data %>
                          </div>


                        </div>
                      </div>
                    </div>

                    <h2 class="wsite-content-title" style="text-align:left;">
                      <strong><%= AboutData.where(:key => "MemberHeader").first.data %></strong></h2>

                    <div class="paragraph" style="text-align:left;"><span
                    style="font-size: 1em; line-height: 1.5;"><%= AboutData.where(:key => "MemberPara1").first.data %></span><br/><br/><span
                    style="font-size: 1em; line-height: 1.5;"></span>
                      <ol style="font-size: 1em; line-height: 1.5;">
                        <% AboutData.where(:key => "MemberList").each do |m| %>
                            <li><%= m.data %></li>
                        <% end %>
                        <!--<li>Mrs. Shiela Bora (daughter)</li>-->
                        <!--<li>Mr. Pranab Barua (son)</li>-->
                        <!--<li> Mrs. Nila Mehta (daughter)</li>-->
                        <!--<li>Mr. Pralab Barua (son)</li>-->
                        <!--<li> Ms. Mala Barua (daughter)</li>-->
                      </ol>
                      <span style="font-size: 1em; line-height: 1.5;"><br/><%= AboutData.where(:key => "MemberPara2").first.data %></span><br/><br/><span
                    style="font-size: 1em; line-height: 1.5;"></span><span
                    style="font-size: 1em; line-height: 1.5;">  				</span>
                      <ol style="font-size: 1em; line-height: 1.5;">
                        <% AboutData.where(:key => "MemberList1").each do |m| %>
                            <li><%= m.data %></li>
                        <% end %>
                        <!--<li>Ms. Nisha Bora (granddaughter)</li>-->
                        <!--<li>Mr. Varun Mehta (grandson)</li>-->
                      </ol>
                    </div>

                  </td>
                </tr>
                </tbody>
              </table>
            </div>
          </div>
        </div>

        <hr>
        <h2 class="wsite-content-title" style="text-align:left;"><strong><%= AboutData.where(:key => "AimHeader").first.data %></strong></h2>

        <div class="paragraph" style="text-align:left;">
          <div style="float: left;width:50%;"><%= AboutData.where(:key => "AimHeaderPara1").first.data %><br/><span
          style=""></span><br/><span style=""></span> <%= AboutData.where(:key => "AimHeaderPara2").first.data %>
          </div>

          <div style="float: right;height:320px;width:400px;">
            <img src="<%= AboutData.where(:key => "Image2").first.avatar.url %>" height="320px"
                 width="400px">
          </div>

          <br/><span style=""></span><br/><span style=""></span></div>

        <div style="text-align:left;margin-top: 40%">
          <div style="height: 10px; overflow: hidden;"></div>


          <a class="wsite-button wsite-button-large wsite-button-highlight"
             href="awards.html">
            <span class="wsite-button-inner">Know More about the Awards</span>
          </a>

          <div style="height: 10px; overflow: hidden;"></div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/home/awards.html.erb
<%= content_for :navbar do %>
    <ul class='wsite-menu-default'>
      <li id='pg102028352772474583'><a href='/'>Home</a></li>
      <li id='pg781891109137199263'><a href='/about'>About</a></li>
      <li id='active'><a href='/awards'>Awards</a></li>
      <li id='pg744403079724393911'><a href='/nomination_procedure'>Nomination Procedure</a></li>
      <li id='pg783104721222161831'><a href='/contact'>Contact</a></li>
    </ul>
<% end %>
<div id="main">
          <div id="main-inner">
            <div id="banner">
              <div id="banner-right">
                <div class="wsite-header"></div>
              </div>
            </div>
            <div id="content">
              <div id='wsite-content' class='wsite-elements wsite-not-footer'>
                <h2 class="wsite-content-title" style="text-align:left;"><strong><%= AwardData.where(:key=>"AwardHeader").first.data %></strong></h2>

                <span class='imgPusher' style='float:left;height:0px'></span><span
              style='z-index:10;position:relative;float:left;max-width:100%;;clear:left;margin-top:0px;*margin-top:0px'><a><img
              src="<%= AwardData.where(:key=>"AwardImage").first.avatar.url %>" width="256px" height="170px"
              style="margin-top: 14px; margin-bottom: 0px; margin-left: 0px; margin-right: 12px; border-width:1px;padding:3px;"
              alt="Picture" class="wsite-image"/></a><span
              style="display: block; font-size: 90%; margin-top: -10px; margin-bottom: 10px; text-align: center;"
              class="wsite-caption"></span></span>

                <div class="paragraph" style="text-align:left;display:block;">
                  <strong style=""><%= AwardData.where(:key => "AwardParaTitle1").first.data %></strong><br/>
                  <%= AwardData.where(:key => "AwardPara1").first.data %><br/><br/>
                  <strong
                style=""><%= AwardData.where(:key => "AwardParaTitle2").first.data %></strong><br/>
                  <%= AwardData.where(:key => "AwardPara2").first.data %>
                </div>
                <hr style="width:100%;clear:both;visibility:hidden;"></hr>

                <div style="text-align:left;">
                  <div style="height: 10px; overflow: hidden;"></div>
                  <a class="wsite-button wsite-button-large wsite-button-highlight"
                     href="nomination-procedure.html">
                    <span class="wsite-button-inner">Nomination Forms and Procedure</span>
                  </a>

                  <div style="height: 10px; overflow: hidden;"></div>
                </div>

                <div>
                  <div style="height: 20px; overflow: hidden; width: 100%;"></div>
                  <hr class="styled-hr" style="width:100%;"></hr>
                  <div style="height: 20px; overflow: hidden; width: 100%;"></div>
                </div>

                <div>
                  <div class="wsite-multicol">
                    <div class='wsite-multicol-table-wrap' style='margin:0 -15px'>
                      <table class='wsite-multicol-table'>
                        <tbody class='wsite-multicol-tbody'>
                        <tr class='wsite-multicol-tr'>
                          <td class='wsite-multicol-col' style='width:50%;padding:0 15px'>

                            <h2 class="wsite-content-title" style="text-align:left;">
                              <strong><%= AwardData.where(:key => "EligibilityHeader").first.data %></strong></h2>

                            <div class="paragraph" style="text-align:left;"><span
                            style="font-size: 1em; line-height: 1.5;"><%= AwardData.where(:key => "EligibilityPara1").first.data %></span>
                              <br/><br/><%= AwardData.where(:key => "EligibilityPara2").first.data %>
                              <ol style="">
                                <% AwardData.where(:key => "EligibilityList").each do |m| %>
                                    <li style=""><%= m.data %></li>
                                <% end %>
                                <!--<li style="">Kaziranga National Park</li>-->
                                <!--<li style="">Manas National Park</li>-->
                                <!--<li style="">Pobitara Wildlife Sanctuary</li>-->
                                <!--<li style="">Orang National Park</li>-->
                              </ol>
                            </div>

                          </td>
                          <td class='wsite-multicol-col' style='width:50%;padding:0 15px'>

                            <h2 class="wsite-content-title" style="text-align:left;">
                              <strong><%= AwardData.where(:key => "ExampleHeader").first.data %></strong></h2>

                            <div class="paragraph" style="text-align:left;">
                              <ol style="">
                                <% AwardData.where(:key => "ExampleList").each do |m| %>
                                    <li style=""><%= m.data %></li>
                                <% end %>
                              </ol>
                            </div>

                          </td>
                        </tr>
                        </tbody>
                      </table>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

app/views/home/contact.html.erb
<%= content_for :navbar do %>
    <ul class='wsite-menu-default'>
      <li id='pg102028352772474583'><a href='/'>Home</a></li>
      <li id='pg781891109137199263'><a href='/about'>About</a></li>
      <li id='pg744403079724393911'><a href='/awards'>Awards</a></li>
      <li id='pg783104721222161831'><a href='/nomination_procedure'>Nomination Procedure</a></li>
      <li id='active'><a href='/contact'>Contact</a></li>
    </ul>
<% end %>
<div id="main">
<div id="main-inner">
  <div id="banner">
    <div id="banner-right">
      <div class="wsite-header"></div>
    </div>
  </div>
  <div id="content">
    <div id='wsite-content' class='wsite-elements wsite-not-footer'>
      <div>
        <div class="wsite-multicol">
          <div class='wsite-multicol-table-wrap' style='margin:0 -15px'>
            <table class='wsite-multicol-table'>
              <tbody class='wsite-multicol-tbody'>
              <tr class='wsite-multicol-tr'>
                <td class='wsite-multicol-col' style='width:50%;padding:0 15px'>

                  <div>
                    <%= form_for(@feedback) do |f| %>
                      <div id="854914594257641426-form-parent"
                           class="wsite-form-container"
                           style="margin-top:10px;">
                        <ul class="formlist"
                            id="854914594257641426-form-list">
                          <h2 class="wsite-content-title"
                              style="text-align:left;"><%= ContactData.where(:key => "ContactHeader").first.data %></h2>

                          <div>
                            <div class="wsite-form-field wsite-name-field"
                                 style="margin:5px 0px 5px 0px;">
                              <label class="wsite-form-label"
                                     for="input-945650361603103125">Name
                                <span class="form-required">*</span></label>

                              <div style="clear:both;"></div>
                              <div class="wsite-form-input-container wsite-form-left wsite-form-input-first-name">
                                <%= f.text_field :firstname, :class=>"wsite-form-input wsite-input" %>
                                <label class="wsite-form-sublabel"
                                       for="input-945650361603103125">First</label>
                              </div>
                              <div class="wsite-form-input-container wsite-form-right wsite-form-input-last-name">
                                <%= f.text_field :lastname, :class=>"wsite-form-input wsite-input" %>
                                <label class="wsite-form-sublabel"
                                       for="input-945650361603103125-1">Last</label>
                              </div>
                              <div id="instructions-945650361603103125"
                                   class="wsite-form-instructions"
                                   style="display:none;"></div>
                            </div>
                            <div style="clear:both;"></div>
                          </div>

                          <div>
                            <div class="wsite-form-field"
                                 style="margin:5px 0px 5px 0px;">
                              <label class="wsite-form-label"
                                     for="input-427503930531593601">Email
                                <span class="form-required">*</span></label>

                              <div class="wsite-form-input-container">
                                <%= f.text_field :email, :class=>"wsite-form-input wsite-input wsite-input-width-370px" %>
                              </div>
                              <div id="instructions-427503930531593601"
                                   class="wsite-form-instructions"
                                   style="display:none;"></div>
                            </div>
                          </div>

                          <div>
                            <div class="wsite-form-field"
                                 style="margin:5px 0px 5px 0px;">
                              <label class="wsite-form-label"
                                     for="input-899500229955225517">Comment
                                <span class="form-required">*</span></label>

                              <div class="wsite-form-input-container">
                                <%= f.text_area :comments, :class=>"wsite-form-input wsite-input wsite-input-width-370px", :style=> "height:200px" %>

                              </div>
                              <div id="instructions-899500229955225517"
                                   class="wsite-form-instructions"
                                   style="display:none;"></div>
                            </div>
                          </div>
                        </ul>
                      </div>
                      <div style="display:none; visibility:hidden;">
                        <input type="text" name="wsite_subject"/>
                      </div>
                      <div style="text-align:left; margin-top:10px; margin-bottom:10px;">
                        <input type="hidden" name="form_version" value="2"/>
                        <input type="hidden" name="wsite_approved"
                               id="wsite-approved" value="approved"/>
                        <input type="hidden" name="ucfid"
                               value="854914594257641426"/>
                        <%= f.submit "Submit" %>
                      </div>
                    <% end %>


                  </div>

                </td>
                <td class='wsite-multicol-col' style='width:50%;padding:0 15px'>

                                            <span class="wsite-content-title" style="text-align:left;">Or drop
                                                a letter to:</span>

                  <div class="paragraph" style="text-align:left;">Mrs. Shiela
                    Bora<br/>
                    House No.2, By-Lane No.2,<br/> K.P.Barua Road, Krishna Nagar,
                    <br/>Chandmari,<br/>Guwadmari - 781003<br/> Mobile No:
                    09435033221<br/></div>

                                            <span class="wsite-content-title" style="text-align:left;">Or
                                                email us at:</span>

                  <div class="paragraph" style="text-align:left;"><span><a href="mailto:shielabora@yahoo.com.">shielabora@yahoo.com</a></span>
                  </div>

                  <div>
                    <div class="wsite-image"
                         style="padding-top:10px;padding-bottom:10px;margin-left:0;margin-right:0;text-align:center">
                      <a>
                        <img src="<%= ContactData.where(:key => "ContactImage").first.avatar.url %>" alt="Picture"
                             style="width:auto;max-width:100%"/>
                      </a>

                      <div style="display:block;font-size:90%"></div>
                    </div>
                  </div>

                </td>
              </tr>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
</div>